# Generated by Django 5.2.3 on 2025-06-24 16:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_alter_cart_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='PK')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField(max_length=50)),
                ('division', models.CharField(choices=[('Bahawalpur', 'Bahawalpur'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gujranwala', 'Gujranwala'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Rawalpindi', 'Rawalpindi'), ('Sahiwal', 'Sahiwal'), ('Sargodha', 'Sargodha')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('FAILED', 'Failed')], max_length=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(to='shop.product')),
            ],
        ),
    ]
