# Generated by Django 5.2.3 on 2025-06-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orders_tracking_token_alter_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('ORDER PLACED', 'Order PLaced'), ('SHIPPED', 'Shipped'), ('OUT FOR DELIVERY', 'Out for Deliverey'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned'), ('FAILED', 'Failed')], default='ORDER PLACED', max_length=30),
        ),
    ]
