# Generated by Django 5.2.3 on 2025-06-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping_fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divison', models.CharField(choices=[('Bahawalpur', 'Bahawalpur'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gujranwala', 'Gujranwala'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Rawalpindi', 'Rawalpindi'), ('Sahiwal', 'Sahiwal'), ('Sargodha', 'Sargodha'), ('other', 'other')], max_length=50)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='payment',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='division',
            field=models.CharField(choices=[('Bahawalpur', 'Bahawalpur'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Faisalabad', 'Faisalabad'), ('Gujranwala', 'Gujranwala'), ('Lahore', 'Lahore'), ('Multan', 'Multan'), ('Rawalpindi', 'Rawalpindi'), ('Sahiwal', 'Sahiwal'), ('Sargodha', 'Sargodha'), ('other', 'other')], max_length=50),
        ),
    ]
