# Generated by Django 5.2.3 on 2025-06-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_cart_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='updated_at',
            new_name='expires_at',
        ),
    ]
