# Generated by Django 5.2.3 on 2025-08-09 18:18

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_updated_at_cart_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='expires_at',
            field=models.DateTimeField(default=shop.models.Cart.default_expires_at),
        ),
    ]
