# Generated by Django 5.2.3 on 2025-08-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_pics',
            name='image',
            field=models.ImageField(upload_to='niazbo/'),
        ),
    ]
