# Generated by Django 5.2.3 on 2025-08-10 12:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_home_pics_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_pics',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
